name: build-and-deply

on: 
  workflow_dispatch:


env: 
  DEPLOY_PATH: 'c:/ws/hw'


jobs:
  build_and_deply:
    runs-on: [self-hosted, win-test-runner-1]

    steps:
      - name: stop iis server
        run: iisreset /stop
        shell: powershell

      - name: build
        run: |
          Remove-Item -Recurse -Force -Path "C:\website\mvc\*"
          dotnet restore
          dotnet build --configuration Release
        shell: powershell

      - name: checkout code
        uses: actions/checkout@v3

      - name: install dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'              

      - name: publish and deploy to IIS
        run: |          
          dotnet publish -c Release -o myapp4
          copy-item -Recurse -Force .\myapp4\* "C:\website\mvc\"
        shell: powershell

      - name: start iis server
        run: iisreset /start
        shell: powershell






