name: web deploy

on: 
  workflow_dispatch:
    inputs:
      env_name:
        type: choice
        required: true
        options:
          - DEV
          - PROD


env: 
  DEPLOY_PATH: 'c:/ws/hw'


jobs:
  build_and_deply:
    runs-on: [self-hosted, webdeploy]
  #  environment: ${{ github.event.inputs.env_name }}

    steps:
      # Remote connection to server via powershell
      # https://docs.microsoft.com/en-us/powershell/scripting/learn/ps101/08-powershell-remoting?view=powershell-7.2
#       - name: stop iis server
#         run: iisreset /stop
#         shell: powershell
        
      - name: checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: build
        run: |
          dotnet restore
          dotnet build --configuration Release
#          Remove-Item -Recurse -Force -Path "${{ secrets.DEPLOY_PATH }}\*"
          
        shell: powershell

      

      # - name: install dotnet
      #  uses: actions/setup-dotnet@v2
      #  with:
      #    dotnet-version: '6.0.x'              

      - name: prepare
        run: |          
          dotnet publish -c Release -o myapp4
          Compress-Archive -Path myapp4 -Update -DestinationPath myapp4.zip
          copy-item -Recurse -Force myapp4.zip C:\
        shell: powershell
        
      - name: publish to remote server
        uses: snsinahub-org/iis-webdeploy@development
        with:
          source: 'C:\myapp4.zip'
          destination: 'C:\ws\hw-sam'
          remote_url: 'https://192.168.1.158:8172/msdeploy.axd?site=hw-dev'
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASS }}

#       - name: start iis server
#         run: iisreset /start
#         shell: powershell






