name: Self hosted Build and release

on: 
  workflow_dispatch:
    inputs:
      version:
        description: none
        type: choice
        required: false
        options:
          - MINOR
          - MAJOR
          - PATCH
jobs:
  build_and_release:
    runs-on: [self-hosted, wiis]


    steps:              
      - name: checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: build
        run: |
          dotnet restore
          dotnet build --configuration Release
        shell: powershell

      - name: prepare
        run: |         
          dotnet publish -c Release -o myapp4          
          cp myapp4/t.exe myapp4/wwwroot/lib
          cp myapp4/t.exe myapp4\wwwroot\lib\bootstrap\dist\
          Compress-Archive -Path myapp4\* -DestinationPath myapp4.zip             
        shell: powershell
      - name: 'Create release'
        id: semver
        uses: "snsinahub-org/semver@v2.3.0"
        with:
          type: "${{ github.event.inputs.version }}"
          prefix: 'v'
          body: 'Create release'
          create-release: 'yes'
          files: |
            myapp4.zip
      - name: print version number
        run: |
          echo "New release: ${{ steps.semver.outputs.version }}" >> $GITHUB_STEP_SUMMARY
      
